### ISSUE TITLE
v1.4.4 missing dist/index

### ISSUE THREAD

**Issue by jimulle** [Vincent-P/react-marked-markdown#57]
in my `package.json` I require `"react-marked-markdown": "^1.4.3"`.
today I ran a clean `npm install` and got version 1.4.4 of react-marked-down. 
it seems version 1.4.4 is missing the `dist` directory when it installs.
for my use-case I rolled back to v1.4.3 via `"react-marked-markdown": "1.4.3"`.

**Comment by Vincent-P** [comment]
Can you paste the error here ?

**Comment by eddiemcleanlux** [comment]
I found the same thing, I think you forgot to run the `prepare` script.

Output from webpack:

```
Error: Cannot find module './dist/index'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/myapp/node_modules/react-marked-markdown/index.js:1:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by Vincent-P** [comment]
Thanks for your reports it's fixed !
